name: allerscan
description: "AllerScan - AI-powered allergen scanner"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.1
  google_mlkit_text_recognition: ^0.14.0
  http: ^1.4.0
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  go_router: ^14.8.1
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  path_provider: ^2.1.5
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
